Exercise 1: Analyzing Carbon Emissions Data 

Imagine you have a dataset containing carbon emissions from various cities in a country over a period of time. The data is organized in a NumPy array where each row represents a year, and each column represents a city. 

Task: 

1. Create a 2D NumPy array that stores carbon emissions (in tons) for 5 cities over 10 years. The data should be random numbers between 1000 and 5000 (use numpy.random.randint). 

2. Find the total emissions for each city over the 10 years. 

3. Find the year with the highest total emissions. 

4. Calculate the average emissions for all cities in a specific year (say, Year 5). 

In [1]:
import numpy as np

In [2]:
emissions_data = np.random.randint(1000, 5000, size=(10, 5))

In [3]:
emissions_data

array([[3118, 1608, 2947, 3483, 1137],
       [1319, 2829, 4931, 2603, 1013],
       [4648, 2898, 2341, 2000, 2716],
       [2630, 2641, 4748, 3787, 4478],
       [1931, 2389, 1617, 4507, 1645],
       [2067, 1488, 1479, 2734, 2075],
       [4457, 3238, 2562, 1260, 3433],
       [2360, 1242, 3151, 1029, 3628],
       [1330, 4686, 1262, 3602, 2489],
       [2649, 2415, 3209, 3852, 3033]])

In [5]:
total_city_wise = emissions_data.sum(axis = 0)
total_city_wise

array([26509, 25434, 28247, 28857, 25647])

In [6]:
total_year_wise = emissions_data.sum(axis = 1)
total_year_wise

array([12293, 12695, 14603, 18284, 12089,  9843, 14950, 11410, 13369,
       15158])

In [8]:
year_max = total_year_wise.argmax()
print(year_max+1)

4


In [10]:
average_emission = emissions_data.mean(axis = 1)
average_emission

array([2458.6, 2539. , 2920.6, 3656.8, 2417.8, 1968.6, 2990. , 2282. ,
       2673.8, 3031.6])

In [11]:
average_emission[4]

2417.8

In [152]:
# Step 2: Find total emissions for each city (sum along the columns) 
city_totals = emissions_data.sum(axis = 0)
city_totals

array([26102, 31227, 30920, 29574, 23997])

In [108]:
city_totals

array([29846, 29828, 31730, 29839, 28912])

In [154]:
year_total = emissions_data.sum(axis=1)

In [156]:
year_total

array([ 8883, 13403, 16665, 12760, 12562, 15536, 15987, 13376, 17890,
       14758])

In [158]:
max_year = np.argmax(year_total)
print(max_year+1)

9


In [160]:
avg_emission= emissions_data[4].mean()
avg_emission

2512.4

In [118]:
emissions_data

array([[4014, 3561, 4588, 3011, 2089],
       [3454, 2128, 3574, 3091, 3101],
       [1975, 1757, 1602, 4244, 2615],
       [3552, 4303, 2986, 4821, 4091],
       [3652, 2344, 2211, 3528, 1437],
       [1289, 4004, 3542, 1693, 4210],
       [2105, 1814, 3485, 3325, 3232],
       [2246, 3662, 2663, 2003, 2678],
       [4596, 2527, 2960, 2524, 1721],
       [2963, 3728, 4119, 1599, 3738]])

In [162]:
mean_of_5th_city = emissions_data[:, 4:].mean()

In [164]:
mean_of_5th_city

2399.7

In [166]:
mean_data = emissions_data.mean(axis = 0)

In [168]:
mean_data

array([2610.2, 3122.7, 3092. , 2957.4, 2399.7])

In [128]:
cityA_mean = mean_data[0]

In [130]:
cityB_mean = mean_data[1]

In [132]:
cityC_mean = mean_data[2]

In [134]:
cityD_mean = mean_data[3]

In [136]:
cityE_mean = mean_data[4]

In [170]:
print(f"total emissions for each city over the 10 years {city_totals}")
print(f"The year with the highest total emissions is {max_year + 1}")
print(f"Average emission for 5th year is {avg_emission}")

total emissions for each city over the 10 years [26102 31227 30920 29574 23997]
The year with the highest total emissions is 9
Average emission for 5th year is 2512.4


Exercise 2: Renewable Energy Growth Analysis 

You’re analyzing the growth of renewable energy production over time. You have data for the percentage of total energy production that comes from renewable sources. 

Task: 

1. Create a NumPy array to represent renewable energy percentages for the last 20 years (between 10% and 60%). 

2. Calculate the overall average renewable energy percentage. 

3. Identify the year(s) where the renewable energy percentage was below 20%. 

4. Find the highest percentage of renewable energy in a single year. 

In [172]:
# Step 1: Generate random renewable energy percentages (20 years) 
renewable_energy = np.random.randint(10, 61, size=20)

In [174]:
renewable_energy

array([31, 15, 19, 29, 60, 40, 34, 55, 53, 36, 57, 41, 55, 49, 56, 32, 40,
       14, 22, 48])

In [176]:
# Step 2: Calculate the overall average renewable energy percentage 
avg_renewable_percentage = renewable_energy.mean()
avg_renewable_percentage

39.3

In [188]:
ren_below = np.where(renewable_energy < 20)[0]
print(ren_below + 1)

[ 2  3 18]


In [192]:
high_per = np.argmax(renewable_energy)
high_per + 1

5

In [76]:
# Step 3: Identify years where renewable energy percentage was below 20% 
below_20_years = np.where(renewable_energy < 20)[0] + 1 # +1 for 1-based indexing 

In [78]:
below_20_years

array([ 1,  2,  9, 14], dtype=int64)

In [80]:
max_production = renewable_energy.max()

In [82]:
max_production

59

In [84]:
max_production_year = np.argmax(renewable_energy)

In [86]:
max_production_year + 1

12

In [ ]:
max_prod_array = np.where(renewable_energy >= max(renewable_energy))[0] + 1

In [ ]:
max_prod_array

Exercise 3: Water Usage Optimization 

You’re tasked with analyzing water usage data for agricultural fields (5 fields) over the course of a year. The data represents water usage (in liters) for each field in each month. 

Task: 

1. Create a 2D NumPy array where each row represents a month, and each column represents a field. Generate random data between 5000 and 20000 liters. 

2. Calculate the total water usage for each field over the year. 

3. Find the month with the highest water usage across all fields. 

4. Calculate the average water usage for all fields in a specific month (e.g., February). 

Exercise 3: Water Usage Optimization 

You’re tasked with analyzing water usage data for agricultural fields over the course of a year. The data represents water usage (in liters) for each field in each month. 

Task: 

Create a 2D NumPy array where each row represents a month, and each column represents a field. Generate random data between 5000 and 20000 liters. 

Calculate the total water usage for each field over the year. 

Find the month with the highest water usage across all fields. 

Calculate the average water usage for all fields in a specific month (e.g., February).  = np.random.randint(5000, 20000, size = (12, 5))

In [194]:
water_usage = np.random.randint(5000, 20000, size = (12, 5))

In [196]:
water_usage

array([[18652,  9115,  6880, 12017,  9663],
       [11399,  8839, 19166, 10044,  6857],
       [17238,  5864,  7069,  9619, 19394],
       [18667, 14957, 10418, 13549, 13091],
       [ 8389,  5304, 10731, 18296,  8874],
       [ 9614, 17009,  8629, 19829, 19953],
       [14448, 17358,  8358,  5397, 19178],
       [18648, 12215, 15275,  8657, 19980],
       [12848, 15300, 13782, 10220, 16692],
       [10912,  8912,  9573, 14725,  6764],
       [15165, 12294, 15263, 17175,  9933],
       [ 6208, 13069,  7820, 13522, 12424]])

In [204]:
ave_monthwise = water_usage.mean(axis = 1)
ave_monthwise[1]

11261.0

In [92]:
total_water_feildwise = water_usage.sum(axis = 0)

In [94]:
total_water_feildwise

array([156055, 123377, 164069, 143354, 148901])

In [96]:
total_water_monthwise = water_usage.sum(axis = 1)

In [98]:
total_water_monthwise

array([51474, 56629, 59202, 53141, 66963, 54870, 77024, 73421, 64731,
       66404, 57167, 54730])

In [ ]:
max(total_water_monthwise)

In [ ]:
max_month = np.argmax(total_water_monthwise) + 1

In [ ]:
max_month

In [ ]:
avg_water_monthwise = water_usage.mean(axis = 1)
avg_water_monthwise

In [ ]:
avg_water_monthwise[1] #For accessing feb month data

Exercise 4: Forest Area Deforestation Rates 

You’re studying the deforestation rates over a decade. Data is recorded on the total forest area (in hectares) lost per year. 

Task: 

1. Create a 1D NumPy array that represents forest area loss over 15 years (random values between 10000 and 50000 hectares). 

2. Find the year with the highest deforestation. 

3. Calculate the total deforestation over the 15 years. 

4. Calculate the average annual deforestation rate. 

In [ ]:
emissions_data.shape[0]

Exercise 3: Waste Management

You are analyzing waste generation data across 6 different sectors (e.g., Residential, Industrial, Commercial, etc.) over the last 5 years. The data is organized in a 2D NumPy array.

Task:
1. Create a 2D NumPy array of shape (5, 6), representing the waste generated (in tons) in each sector for each of the last 5 years. Populate it with random data between 1000 and 5000 tons.
   
2. Calculate the total waste generated by each sector over the 5 years.

3. Identify the year with the highest total waste generation.

4. Find the sector with the lowest waste generation in a specific year (e.g., Year 3).

5. Normalize the waste data so that each sector’s waste data is scaled between 0 and 1 (using Min-Max scaling).

In [ ]:
waste_data = np.random.randint(1000, 5000, size = (5, 6))

In [ ]:
waste_data

In [ ]:
total_waste_generated_by_each_sector = waste_data.sum(axis = 0)
total_waste_generated_by_each_sector

In [ ]:
total_waste_generated_by_year = waste_data.sum(axis = 1)
total_waste_generated_by_year

In [ ]:
max(total_waste_generated_by_year)

In [ ]:
max_waste_year = np.argmax(total_waste_generated_by_year) + 1
max_waste_year

In [ ]:
low_waste_gen = waste_data[2]
low_waste_gen

In [ ]:
sector_with_low_gen = np.argmax(low_waste_gen) + 1
sector_with_low_gen

In [ ]:
min_data = waste_data.min(axis = 0)
max_data = waste_data.max(axis = 0)
std_data = (waste_data - min_data) / (max_data - min_data)
print(np.round(std_data, 2))

In [ ]:
energy_data = np.random.randint(50, 300, size = (12, 3))
energy_data

In [ ]:
high_avg_device = energy_data.mean(axis = 0)
high_avg_device

In [ ]:
high_avg_energy_usage = np.argmin(high_avg_device) + 1

In [ ]:
high_avg_energy_usage

In [ ]:
max_usage_month = energy_data.max(axis = 1)
max_usage_month