##NUMPY

In [2]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print(type(arr))


print("Sum:", np.sum(arr))


print("Mean:", np.mean(arr))


print("Multiplied by 2:", arr * 2)


matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

print("Transpose:\n", matrix.T)

arr.size


Array: [1 2 3 4 5]
<class 'numpy.ndarray'>
Sum: 15
Mean: 3.0
Multiplied by 2: [ 2  4  6  8 10]
Matrix:
 [[1 2]
 [3 4]]
Transpose:
 [[1 3]
 [2 4]]


5

In [3]:
weekly_temp = np.random.randint(20,40,size = (7))
print(weekly_temp)

[37 22 29 26 30 23 34]


In [21]:
water_consumption = np.random.randint(1000,5000,size = (4,6))
print(water_consumption)
print(water_consumption.transpose())
print(water_consumption.flatten())
sum_of_data = water_consumption.sum()
sum_of_data


[[3357 1463 2084 3283 2873 2190]
 [4123 2734 1571 1903 4765 2700]
 [1280 4255 1872 3454 1412 2407]
 [3910 2013 2798 3120 4965 3565]]
[[3357 4123 1280 3910]
 [1463 2734 4255 2013]
 [2084 1571 1872 2798]
 [3283 1903 3454 3120]
 [2873 4765 1412 4965]
 [2190 2700 2407 3565]]
[3357 1463 2084 3283 2873 2190 4123 2734 1571 1903 4765 2700 1280 4255
 1872 3454 1412 2407 3910 2013 2798 3120 4965 3565]


np.int64(68097)

In [26]:
month_total = water_consumption.sum(axis = 0)
month_total

array([12670, 10465,  8325, 11760, 14015, 10862])

In [ ]:
month_total.argmax() + 1

np.int64(5)

In [33]:
month_total.argmin() + 1

np.int64(3)

In [27]:
building_total = water_consumption.sum(axis = 1)
building_total

array([15250, 17796, 14680, 20371])

In [28]:
#Mean value
avg_month_wise = water_consumption.mean(axis=0)
avg_month_wise

array([3167.5 , 2616.25, 2081.25, 2940.  , 3503.75, 2715.5 ])

In [30]:
avg_bdlg_wise = water_consumption.mean(axis=1)
avg_bdlg_wise
np.round(avg_bdlg_wise,2)

array([2541.67, 2966.  , 2446.67, 3395.17])

In [35]:
print(water_consumption.std())
print(water_consumption.var())


1043.8763421537692
1089677.8177083333


In [22]:
zeros_arr = np.zeros(12)
zeros_arr.reshape(4,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
ones_arr = np.ones(16)
ones_arr.reshape(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
a = np.random.randint(20,50,size = (3,3))
b = np.random.randint(20,50,size = (3,3))
addition = np.add(a,b)
print(addition)
multiplication = np.multiply(a,b)
print(multiplication)
substraction = np.subtract(a,b)
print(substraction)
division = np.divide(a,b)
print(division)
exponential = np.power(a,b)
print(exponential)



[[75 85 73]
 [74 85 72]
 [86 58 82]]
[[1316 1794 1330]
 [1368 1764 1287]
 [1813  816 1680]]
[[-19   7   3]
 [ -2 -13  -6]
 [-12 -10  -2]]
[[0.59574468 1.17948718 1.08571429]
 [0.94736842 0.73469388 0.84615385]
 [0.75510204 0.70588235 0.95238095]]
[[         0          0          0]
 [         0          0    9771233]
 [-672150939          0          0]]


In [25]:
sum_of_data = water_consumption.sum()
sum_of_data

np.int64(68097)

In [ ]:
# # Exercise 1: Analyzing Carbon Emissions Data
# # Imagine you have a dataset containing carbon emissions from various cities in a country over a period of time. The data is organized in a NumPy array where each row represents a year, and each column represents a city.
# # Task:
# # 1.	Create a 2D NumPy array that stores carbon emissions (in tons) for 5 cities over 10 years. The data should be random numbers between 1000 and 5000 (use numpy.random.randint).
# # 2.	Find the total emissions for each city over the 10 years.
# # 3.	Find the year with the highest total emissions.
# # 4.	Calculate the average emissions for all cities in a specific year (say, Year 5).

import numpy as np

carbon_emissions = np.random.randint(1000, 5001, size=(10, 5))
print("Carbon Emissions Data (10 years, 5 cities):", carbon_emissions)

total_emissions_per_city = np.sum(carbon_emissions, axis=0)
print("\nTotal Emissions for each city over 10 years:\n", total_emissions_per_city)

total_emissions_per_year = np.sum(carbon_emissions, axis=1)
print("\nTotal Emissions for each year:\n", total_emissions_per_year)
year_with_highest_emissions_index = np.argmax(total_emissions_per_year)

year_with_highest_emissions = year_with_highest_emissions_index + 1
print(f"\nYear with the highest total emissions: Year {year_with_highest_emissions}")

year_5_emissions = carbon_emissions[4, :]
average_emissions_year_5 = np.mean(year_5_emissions)
print(f"\nEmissions in Year 5 (all cities):\n{year_5_emissions}")
print(f"Average emissions for all cities in Year 5: {average_emissions_year_5:.2f} tons")

Carbon Emissions Data (10 years, 5 cities): [[3395 1146 4531 2442 1906]
 [4081 1839 3990 1157 3358]
 [2430 4730 2260 3173 3463]
 [4871 4533 1703 3618 2777]
 [4437 4645 2884 4952 3563]
 [2260 2218 3051 3446 3776]
 [1154 3766 3589 3911 4541]
 [3272 3617 4517 4340 1278]
 [2478 4349 2677 1290 4726]
 [3176 2685 1930 1731 2468]]

Total Emissions for each city over 10 years:
 [31554 33528 31132 30060 31856]

Total Emissions for each year:
 [13420 14425 16056 17502 20481 14751 16961 17024 15520 11990]

Year with the highest total emissions: Year 5

Emissions in Year 5 (all cities):
[4437 4645 2884 4952 3563]
Average emissions for all cities in Year 5: 4096.20 tons


In [ ]:
# Exercise 2: Water Usage Optimization
# You’re tasked with analyzing water usage data for agricultural fields (5 fields) over the course of a year. The data represents water usage (in liters) for each field in each month.
# Task:
# 1.	Create a 2D NumPy array where each row represents a month, and each column represents a field. Generate random data between 5000 and 20000 liters.
# 2.	Calculate the total water usage for each field over the year.
# 3.	Find the month with the highest water usage across all fields.
# 4.	Calculate the average water usage for all fields in a specific month (e.g., February).