In [1]:
import numpy as np
arr2d = np.random.randint(10,30,size =(4,4))
arr2d

array([[17, 16, 17, 10],
       [17, 22, 13, 25],
       [20, 19, 14, 24],
       [23, 20, 15, 25]], dtype=int32)

In [6]:
import numpy as np
arr3d = np.random.randint(10,30,size =(4,3,4))
print(arr3d)
print(arr3d[-2,-1,-1])

[[[17 16 26 17]
  [22 24 18 10]
  [26 10 19 25]]

 [[13 11 13 10]
  [19 28 28 27]
  [14 28 17 13]]

 [[22 19 24 22]
  [10 24 14 26]
  [16 17 28 26]]

 [[12 11 18 10]
  [10 19 20 25]
  [16 11 12 21]]]
26


In [22]:
import numpy as np
arr1d = np.random.randint(10,30,size=(10))
print(arr1d)
print(arr1d[4])
arr2d = np.random.randint(10,30,size=(3,4))
print(arr2d)
print(arr2d[2,2])



[27 26 11 15 10 23 24 15 21 21]
10
[[13 26 22 21]
 [16 21 18 15]
 [14 11 20 13]]
20


In [23]:
arr3d = np.random.randint(10,30,size=(2,2,3))
print(arr3d)
print(arr3d[-1,-1,-2])
print(arr3d[1,1,2])

[[[25 17 21]
  [29 24 18]]

 [[10 11 11]
  [24 19 15]]]
19
15


In [ ]:
#Numpy array slicing 
#Creating numpy array using arrange() and linspace()
resource = np.arange(10,50)
new = resource.reshape(8,5)
new[5:,1:]
#new[4:6,:]
# new[4:6,-2:] 

array([[36, 37, 38, 39],
       [41, 42, 43, 44],
       [46, 47, 48, 49]])

In [30]:
x = np.linspace(10,100,24)
print(x.shape)
print(x.reshape(6,4))
print(x.reshape(3,2,4))

(24,)
[[ 10.          13.91304348  17.82608696  21.73913043]
 [ 25.65217391  29.56521739  33.47826087  37.39130435]
 [ 41.30434783  45.2173913   49.13043478  53.04347826]
 [ 56.95652174  60.86956522  64.7826087   68.69565217]
 [ 72.60869565  76.52173913  80.43478261  84.34782609]
 [ 88.26086957  92.17391304  96.08695652 100.        ]]
[[[ 10.          13.91304348  17.82608696  21.73913043]
  [ 25.65217391  29.56521739  33.47826087  37.39130435]]

 [[ 41.30434783  45.2173913   49.13043478  53.04347826]
  [ 56.95652174  60.86956522  64.7826087   68.69565217]]

 [[ 72.60869565  76.52173913  80.43478261  84.34782609]
  [ 88.26086957  92.17391304  96.08695652 100.        ]]]


In [38]:
import numpy as np


arr1d = np.arange(20)
arr2d = np.arange(20).reshape(4, 5) 
arr3d = np.arange(24).reshape(2, 3, 4)

print(f"1D: {arr1d}\n2D:\n{arr2d}\n3D:\n{arr3d}\n")


print("1D Slicing ")
print(f"arr1d[5:12]: {arr1d[5:12]}\n")
print(f"arr1d[::3]: {arr1d[::3]} (with step)\n")


print("2D Slicing")
print(f"arr2d[1:3, 0:3]:\n{arr2d[1:3, 0:3]} (rows 1-2, cols 0-2)\n")

print("3D Slicing")
print(f"arr3d[0, 1, 1:3]: {arr3d[0, 1, 1:3]} (elements in 1st matrix, 2nd row)\n")


print("Negative Slicing")
print(f"arr1d[-5:] (1D): {arr1d[-5:]}\n")
print(f"arr2d[-2:, -3:] (2D):\n{arr2d[-2:, -3:]}\n")
print(f"arr3d[-1, -2:, -3:] (3D):\n{arr3d[-1, -2:, -3:]}\n")


print("Comparison")
print(f"1D: arr1d[-5:] ({arr1d[-5:]}) vs arr1d[15:] ({arr1d[15:]})\n")
print("Negative indexing counts from the end.")


1D: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2D:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
3D:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

1D Slicing 
arr1d[5:12]: [ 5  6  7  8  9 10 11]

arr1d[::3]: [ 0  3  6  9 12 15 18] (with step)

2D Slicing
arr2d[1:3, 0:3]:
[[ 5  6  7]
 [10 11 12]] (rows 1-2, cols 0-2)

3D Slicing
arr3d[0, 1, 1:3]: [5 6] (elements in 1st matrix, 2nd row)

Negative Slicing
arr1d[-5:] (1D): [15 16 17 18 19]

arr2d[-2:, -3:] (2D):
[[12 13 14]
 [17 18 19]]

arr3d[-1, -2:, -3:] (3D):
[[17 18 19]
 [21 22 23]]

Comparison
1D: arr1d[-5:] ([15 16 17 18 19]) vs arr1d[15:] ([15 16 17 18 19])

Negative indexing counts from the end.


In [10]:
import numpy as np
carbon_emissions = np.random.randint(1000,5000,size = (5,10))
print(carbon_emissions)
total_emissions = carbon_emissions.sum(axis = 0)
print("Total emissions for each city over the 10 years: ", total_emissions)
year_total = carbon_emissions.sum(axis = 1)
print(year_total)
year_total = carbon_emissions.mean(axis = 1)
print(year_total)

[[4465 4035 4295 1396 2905 1668 3264 1034 4776 4438]
 [4867 4080 1602 4626 3565 4344 4720 4580 2772 3511]
 [4579 3126 1886 3696 1295 1207 3197 1039 2382 3225]
 [4615 3779 4206 4997 4487 4450 2094 1778 4620 2131]
 [1059 4255 3060 1550 2494 2313 3425 3497 2377 2765]]
Total emissions for each city over the 10 years:  [19585 19275 15049 16265 14746 13982 16700 11928 16927 16070]
[32276 38667 25632 37157 26795]
[3227.6 3866.7 2563.2 3715.7 2679.5]


In [13]:
y = 1
for year in carbon_emissions:
    year_avg = year.mean()
    print(f"The Average emission of year {y} is {year_avg} kgCO2")
    y = y + 1

The Average emission of year 1 is 3227.6 kgCO2
The Average emission of year 2 is 3866.7 kgCO2
The Average emission of year 3 is 2563.2 kgCO2
The Average emission of year 4 is 3715.7 kgCO2
The Average emission of year 5 is 2679.5 kgCO2


In [17]:
import numpy as np

renewable_percentages = np.random.randint(10, 60, size=20)
print("Renewable Energy Percentages :")
print(renewable_percentages)


average_percentage = np.mean(renewable_percentages)
print("\nOverall Average Renewable Energy Percentage:")
print(f"{average_percentage:.2f}%")


below_20_indices = np.where(renewable_percentages < 20)[0]
print("\nYears with Renewable Energy Percentage Below 20%:")
if below_20_indices.size > 0:
    print("Year(s):", below_20_indices + 1)  
    print("Percentages:", renewable_percentages[below_20_indices])
else:
    print("No year had renewable energy below 20%.")


max_percentage = np.max(renewable_percentages)
max_year = np.argmax(renewable_percentages) + 1
print("\nHighest Renewable Energy Percentage in a Single Year:")
print(f"{max_percentage:.2f}% in Year {max_year}")


Renewable Energy Percentages :
[48 27 30 47 21 59 43 12 30 34 48 57 44 33 58 35 32 48 31 16]

Overall Average Renewable Energy Percentage:
37.65%

Years with Renewable Energy Percentage Below 20%:
Year(s): [ 8 20]
Percentages: [12 16]

Highest Renewable Energy Percentage in a Single Year:
59.00% in Year 6


In [18]:
import numpy as np

ren_energy_percentage = np.random.randint(10, 60, 20)
print(ren_energy_percentage)

ren_energy_percentage_avg = np.average(ren_energy_percentage)
print(ren_energy_percentage_avg)

year = np.where(ren_energy_percentage < 20)
print(year)

highest_percentage = np.max(ren_energy_percentage)
print(highest_percentage)

[51 24 58 59 52 33 48 28 17 33 20 56 27 13 59 59 23 39 42 31]
38.6
(array([ 8, 13]),)
59


In [19]:
forest_area = np.random.randint(10000 ,50000,size=15)
print(forest_area)
highest_deforestation = np.max(forest_area)
print(highest_deforestation)
total_deforestation = np.sum(forest_area)
print(total_deforestation)
avg_deforestation = np.average(forest_area)
print(avg_deforestation)

[48098 35804 47563 33103 22875 48380 19765 21901 47977 46928 13603 24532
 46592 35705 23822]
48380
516648
34443.2


In [21]:
salary = np.random.randint(20000, 50000, size=(5, 3)) 
scaled_data = (salary - salary.min(axis = 0)) / (salary.max(axis = 0) - salary.min(axis = 0))
print(scaled_data)

[[0.         0.18287572 0.02790624]
 [1.         1.         0.16217509]
 [0.07091813 0.80386622 1.        ]
 [0.74627156 0.         0.        ]
 [0.26949666 0.34154478 0.86323287]]


In [27]:
# Exercise 5: Waste Management
# You are analyzing waste generation data across 6 different sectors (e.g., Residential, Industrial, Commercial, etc.) over the last 5 years. The data is organized in a 2D NumPy array.
# Task:
# 1.	Create a 2D NumPy array of shape (5, 6), representing the waste generated (in tons) in each sector for each of the last 5 years. Populate it with random data between 1000 and 5000 tons.
# 2.	Calculate the total waste generated by each sector over the 5 years.
# 3.	Identify the year with the highest total waste generation.
# 4.	Find the sector with the lowest waste generation in a specific year (e.g., Year 3).
# 5.	Normalize the waste data so that each sector’s waste data is scaled between 0 and 1 (using Min-Max scaling).
import numpy as np

waste_data = np.random.randint(1000, 5000, size = (5, 6))
print(waste_data)

total_waste = np.sum(waste_data, axis = 0)
print(total_waste)

year_with_highest_waste = np.argmax(total_waste) + 1
print(year_with_highest_waste)

lowest_waste_year = 3
lowest_waste_sector = np.argmin(waste_data[lowest_waste_year - 1])
print(lowest_waste_sector)

scaled_data = (waste_data - waste_data.min(axis = 0)) / (waste_data.max(axis = 0) - waste_data.min(axis = 0))
print(scaled_data)


[[2139 3736 2846 2321 1753 3757]
 [3795 2798 1708 4164 2507 1466]
 [4630 1113 1184 1339 2341 3265]
 [3538 2023 3527 3249 1456 4112]
 [3132 3253 4727 3598 4778 3305]]
[17234 12923 13992 14671 12835 15905]
1
1
[[0.         1.         0.46909399 0.34761062 0.08940397 0.86583522]
 [0.66479326 0.64239421 0.14789726 1.         0.31637568 0.        ]
 [1.         0.         0.         0.         0.26640578 0.67989418]
 [0.56162184 0.346931   0.66130398 0.67610619 0.         1.        ]
 [0.39863509 0.8158597  1.         0.79964602 1.         0.69501134]]
